### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by JadoJodo** [mikecrittenden/duckduckgoog#11]

**Comment by vitorgalvao** [comment]
[Context from @mikecrittenden on Twitter](https://twitter.com/mcrittenden/status/1018981154056298500):

> Yeah I let it expire because I ran into some SSL issues and realized that I only really used a few search engines so I should just set them up in Chrome. That said, a few people have reached out, so I will see if I can set it up on a free plan somewhere.

**Comment by mikecrittenden** [comment]
Hey all, yeah, all is fine! I just have stopped using duckduckgoog and didn't realize that anyone else was even using it these days. I don't know that I'll have time to fiddle with getting it back up and running on new hosting with updated dependencies and what not like I wanted, so someone else is more than welcome to fork the repo and take the project over. If you do, just post your new link here and I'll link this repo to yours.

**Comment by crittermike** [comment]
Awesome! I updated the repo description and README to point to yours. I'll leave this issue open for a while as well for visibility.

**Comment by vitorgalvao** [comment]
@mikecrittenden Wouldn’t it make more sense to transfer ownership of the repo?

I don’t think any user cares about the project’s dependencies and whatnot, they care that the page currently doesn’t work.

Instead of changing your README to recommend the fork of the first random person that wants it, it might be a better idea to ask for someone to submit a PR that fixes what needs to be fixed. The person that does it *right* will have the PR merged as well as repo and domain ownership transferred to them, because they proved they have at least the technical chops to keep the project running.

Rushed transfers of projects are what caused the uBlock/uBlock Origin debacle.

**Comment by crittermike** [comment]
For anyone following this, it's back up at https://duckduckgoog.com/ now thanks to https://twitter.com/m_held

**Comment by TPS** [comment]
@mikecrittenden Thanks ___very___ much!  I suppose this solves this issue & #10 in 1 shot, so close?

**Comment by crittermike** [comment]
Yep!
