### ISSUE TITLE
Detect [words] ! (alone exclamation mark) as I'm Feeling Lucky

### ISSUE THREAD

**Issue by underr** [mikecrittenden/duckduckgoog#8]
If you search for [this](https://duckduckgo.com/?q=google !) (**google !**) on DDG, it will redirect you to Google, as it's the DDG shortcut to the **I'm Feeling Lucky** option.
duckduckgoog don't, but it should if you are trying to replicate DDG's behavior.

**Comment by mikecrittenden** [comment]
It works if you do the ! at the beginning. It used to work if the ! was at
the end too but I had people complain because it's fairly common,
especially for non-native english speakers, to end a sentence with a space
before punctuation, so people would copy/paste something that had that in
there and get kicked to the feeling lucky result, which isn't the desired
behavior. So for now, I'm going to stick with only using feeling lucky if
the "!" is the first character.

**Comment by underr** [comment]
I didn't noticed, thanks. Closing.
